import {$,node,table,stamp} from '/assets/components/cards.js';
const fields=['registered_population','meal_capacity','safety_margin_pct','minimum_protein','calorie_min','calorie_max','sodium_max'];
let loading=false,loadedFor=null;
const day=new Date();day.setDate(day.getDate()+1);$('admin-date').value=`${day.getFullYear()}-${String(day.getMonth()+1).padStart(2,'0')}-${String(day.getDate()).padStart(2,'0')}`;
async function call(method='GET',body){const response=await fetch(`/api/admin/settings/${encodeURIComponent($('admin-site').value)}?target_date=${$('admin-date').value}`,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw new Error(data.message);return data;}
function render(data){for(const field of fields)$(field).value=data.settings[field];$('allergy_restriction').value=data.settings.allergy_restriction.join(', ');$('recipes').replaceChildren();$('prices').replaceChildren();table($('recipes'),[['메뉴','menu'],['식재료','ingredient'],['1인분 기준',r=>`${r.amount}${r.unit}`]],data.recipes.flatMap(r=>r.ingredients.map(i=>({menu:r.menu,...i}))),'등록 레시피');table($('prices'),[['식재료','ingredient'],['가격',r=>`${r.price.toLocaleString('ko-KR')}원/${r.unit}`],['기준일','date']],data.prices,'등록 가격');}
const contextKey=()=>$('admin-site').value+'|'+$('admin-date').value;
async function task(fn){if(loading)return;loading=true;$('admin-status').textContent='처리 중…';$('save-settings').disabled=true;$('admin-site').disabled=true;$('admin-date').disabled=true;try{await fn();}catch(error){$('admin-status').textContent=error.message;$('admin-status').classList.add('error');}finally{loading=false;$('save-settings').disabled=loadedFor!==contextKey();$('admin-site').disabled=false;$('admin-date').disabled=false;}}
const load=()=>task(async()=>{loadedFor=null;$('settings-form').reset();$('recipes').replaceChildren();$('prices').replaceChildren();const data=await call();render(data);loadedFor=contextKey();$('admin-status').classList.remove('error');$('admin-status').textContent=data.updated_at?`${stamp(data.updated_at)}에 저장한 설정입니다.`:'기본 등록 설정입니다.';});
$('admin-site').addEventListener('change',load);$('admin-date').addEventListener('change',load);
$('settings-form').addEventListener('submit',event=>{event.preventDefault();task(async()=>{const settings=Object.fromEntries(fields.map(f=>[f,Number($(f).value)]));settings.allergy_restriction=$('allergy_restriction').value.split(',').map(s=>s.trim()).filter(Boolean);const data=await call('PUT',settings);render(data);$('admin-status').classList.remove('error');$('admin-status').textContent='설정을 저장했습니다. 계획 생성 화면에서 ‘등록 자료로 새로 준비’를 누르면 반영됩니다.';});});
(async()=>{const data=await(await fetch('/api/ui/sites')).json();$('admin-site').replaceChildren(...data.sites.map(s=>new Option(s.name,s.id)));load();})().catch(error=>$('admin-status').textContent=error.message);
